apiVersion: v1
kind: Namespace
metadata:
  name: counter-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-service
  namespace: counter-service  
  labels:
    app: counter-service
    version: blue
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: counter-service
      version: blue
  template:
    metadata:
      labels:
        app: counter-service
        version: blue
    spec:
      containers:
      - name: counter-service
        image: 881490090336.dkr.ecr.eu-west-3.amazonaws.com/checkpoint-task:1.0.3
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m" 
            memory: "256Mi" 
          limits:
            cpu: "500m"  
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: counter-service
  namespace: counter-service 
  labels:
    app: counter-service
spec:
  type: LoadBalancer
  selector:
    app: counter-service
    version: blue
  ports:
    - protocol: TCP
      port: 80      
      targetPort: 8080
