name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main  # Trigger on push to main branch
    paths-ignore:
      - VERSION  # Ignore pushes that only modify the VERSION file
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Step 2: Validate Kubernetes YAMLs
      - name: Validate YAML files
        run: |
          curl -LO https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          chmod +x kubeval
          # Find all .yaml files and validate them
          find . -name "*.yaml" -print0 | xargs -0 ./kubeval

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Extract and Increment Version
      - name: Increment Version
        id: version
        run: |
          # Extract current version or initialize to 0.0.0
          VERSION=$(cat VERSION || echo "0.0.0")
          # Split version into components
          MAJOR=$(echo "$VERSION" | cut -d. -f1)
          MINOR=$(echo "$VERSION" | cut -d. -f2)
          PATCH=$(echo "$VERSION" | cut -d. -f3)
          # Increment patch version
          NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
          echo "New version: $NEW_VERSION"
          # Save new version to VERSION file
          echo "$NEW_VERSION" > VERSION
          echo "version=$NEW_VERSION" >> $GITHUB_ENV
      
      # Step 5: Retrieve the ECR url
      - name: Retrieve ECR Name
        run: |
          ecr_uri=$(aws ssm get-parameter --name /checkpoint/ecr_repository --query "Parameter.Value" --output text)
          echo "ECR Repository URL: $ecr_uri"
          echo "ecr_uri=$ecr_uri" >> $GITHUB_ENV

        # Step 6: Retrieve EKS Cluster Name
      - name: Retrieve EKS Cluster Name
        run: |
          eks_cluster=$(aws ssm get-parameter --name /checkpoint/eks_cluster --query "Parameter.Value" --output text)
          echo "EKS Cluster Name: $eks_cluster"
          echo "eks_cluster=$eks_cluster" >> $GITHUB_ENV

      # Step 7: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 8: Build and tag the Docker image
      - name: Build Docker image
        run: |
          # Use incremented version from environment variable
          docker build -t "$ecr_uri:latest" -t "$ecr_uri:${{ env.version }}" .

      # Step 9: Push the Docker image to ECR
      - name: Push Docker image to Amazon ECR
        run: |
          # Push Docker image to ECR
          docker push "$ecr_uri:${{ env.version }}"

      # Step 10: Commit and Tag New Version
      - name: Commit and Tag New Version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add VERSION
          git commit -m "Increment version to ${{ env.version }}"
          git tag "v${{ env.version }}"
          git push origin main --tags

      # Step 11: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          # Ensure the VERSION file exists
          if [[ ! -f VERSION ]]; then
            echo "Error: VERSION file not found."
            exit 1
          fi

          # Read the version from the VERSION file
          VERSION=$(cat VERSION)

          # Validate that the VERSION is not empty
          if [[ -z "$VERSION" ]]; then
            echo "Error: VERSION file is empty. Please provide a valid version."
            exit 1
          fi

          echo "Deploying version: $VERSION"
          
          # Define the ECR repository URI
          REPOSITORY_URI="${{ env.ecr_uri }}"

          # Update the Kubernetes manifest with the correct image version
          sed -i.bak "s|image: .*:.*|image: $REPOSITORY_URI:$VERSION|" counter-service.yaml

          # Update kubeconfig to use the correct context
          aws eks update-kubeconfig --region eu-west-3 --name "${{ env.eks_cluster }}"

          # Apply the updated manifest to the Kubernetes cluster
          kubectl apply -f counter-service.yaml

          echo "Deployment applied with image version: $VERSION"

